// src/core/components/CameraViewer.tsx
import CircularProgress from '@material-ui/core/CircularProgress'
import { createStyles, makeStyles, Theme } from '@material-ui/core/styles'
import VideocamOffIcon from '@material-ui/icons/VideocamOff'
import { SyntheticEvent, useEffect, useRef, useState } from 'react'
import { CameraPlayback } from '../helpers/cameraHelper'

type CameraViewerProps = {
  onLoad: (cameraPlayback: CameraPlayback) => void
}

function CameraViewer(props: CameraViewerProps) {
  const classes = useStyles()
  const [isLoading, setLoading] = useState(true)
  const [isCameraError, setCameraError] = useState(false)
  const videoRef = useRef<HTMLVideoElement>(null)

  useEffect(() => {
    const videoElement = videoRef.current
    let cameraStream: MediaStream | undefined
    let isCancelled = false

    async function getCameraStream() {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({
          video: true,
        })

        if (isCancelled) {
          stream.getTracks().forEach((track) => track.stop())
          return
        }

        cameraStream = stream

        if (videoElement) {
          videoElement.srcObject = stream
          videoElement.play().catch(() => {
            // Muted autoplay should work, but some browsers still reject the
            // promise until playback actually begins.
          })
        }
      } catch (error) {
        console.error('Error opening video camera.', error)
        if (!isCancelled) {
          setLoading(false)
          setCameraError(true)
        }
      }
    }

    getCameraStream()

    return () => {
      isCancelled = true
      cameraStream?.getTracks().forEach((track) => track.stop())

      if (videoElement) {
        videoElement.srcObject = null
      }
    }
  }, [])

  function handleVideoLoad(event: SyntheticEvent<HTMLVideoElement>) {
    const video = event.currentTarget
    props.onLoad({
      htmlElement: video,
      width: video.videoWidth,
      height: video.videoHeight,
    })
    setLoading(false)
  }

  return (
    <div className={classes.root}>
      {isLoading && <CircularProgress />}
      {isCameraError ? (
        <VideocamOffIcon fontSize="large" />
      ) : (
        <video
          ref={videoRef}
          className={classes.cameraPlayback}
          hidden={isLoading}
          autoPlay
          playsInline
          controls={false}
          muted
          onLoadedMetadata={handleVideoLoad}
        />
      )}
    </div>
  )
}

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      position: 'relative',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',

      [theme.breakpoints.down('xs')]: {
        width: 0,
        overflow: 'hidden',
      },

      [theme.breakpoints.up('sm')]: {
        flex: 1,
        borderRightWidth: 1,
        borderRightStyle: 'solid',
        borderRightColor: theme.palette.divider,
      },
    },
    cameraPlayback: {
      position: 'absolute',
      width: '100%',
      height: '100%',
      objectFit: 'cover',
    },
  })
)

export default CameraViewer

// src/core/components/CameraViewer.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { type CameraPlayback } from '../helpers/cameraHelper'

const emit = defineEmits<{
  load: [CameraPlayback]
}>()

const videoRef = ref<HTMLVideoElement | null>(null)
const isLoading = ref(true)
const isCameraError = ref(false)

let cameraStream: MediaStream | undefined
let isCancelled = false
let hasEmittedLoad = false

async function openCamera() {
  try {
    const stream = await navigator.mediaDevices.getUserMedia({
      video: true,
    })

    if (isCancelled) {
      stream.getTracks().forEach((track) => track.stop())
      return
    }

    cameraStream = stream

    if (videoRef.value) {
      videoRef.value.srcObject = stream
      videoRef.value.play().catch(() => {
        // Muted autoplay should work, but some browsers still reject the
        // promise until playback starts.
      })
    }
  } catch (error) {
    console.error('Error opening video camera.', error)
    if (!isCancelled) {
      isLoading.value = false
      isCameraError.value = true
    }
  }
}

function handleLoadedMetadata() {
  if (!videoRef.value || hasEmittedLoad) {
    return
  }

  hasEmittedLoad = true
  emit('load', {
    htmlElement: videoRef.value,
    width: videoRef.value.videoWidth,
    height: videoRef.value.videoHeight,
  })
  isLoading.value = false
}

onMounted(() => {
  void openCamera()
})

onBeforeUnmount(() => {
  isCancelled = true
  cameraStream?.getTracks().forEach((track) => track.stop())
  cameraStream = undefined

  if (videoRef.value) {
    videoRef.value.srcObject = null
  }
})
</script>

<template>
  <div class="camera-viewer">
    <div v-if="isLoading" class="camera-viewer__spinner" aria-hidden="true"></div>
    <p v-if="isCameraError" class="camera-viewer__message">
      Camera access was denied or is unavailable.
    </p>
    <video
      v-else
      ref="videoRef"
      class="camera-viewer__video"
      :hidden="isLoading"
      autoplay
      playsinline
      muted
      @loadedmetadata="handleLoadedMetadata"
    />
  </div>
</template>

<style scoped>
.camera-viewer {
  position: relative;
  min-height: 16rem;
  display: flex;
  align-items: center;
  justify-content: center;
  background:
    radial-gradient(circle at top, rgba(108, 232, 199, 0.1), transparent 38%),
    linear-gradient(180deg, rgba(2, 6, 23, 0.22), rgba(2, 6, 23, 0.42));
}

.camera-viewer__video {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.camera-viewer__spinner {
  width: 2.75rem;
  height: 2.75rem;
  border-radius: 50%;
  border: 3px solid rgba(255, 255, 255, 0.12);
  border-top-color: var(--accent);
  animation: spin 1s linear infinite;
}

.camera-viewer__message {
  position: relative;
  z-index: 1;
  padding: 1.5rem;
  color: var(--muted);
  text-align: center;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
</style>
