// src/core/components/OutputViewer.vue
<script setup lang="ts">
import { computed, toRef, watch } from 'vue'
import type { BodyPix } from '@tensorflow-models/body-pix'
import { type BackgroundConfig } from '../helpers/backgroundHelper'
import { type PostProcessingConfig } from '../helpers/postProcessingHelper'
import { type SegmentationConfig } from '../helpers/segmentationHelper'
import { type CameraPlayback } from '../helpers/cameraHelper'
import { useRenderingPipeline } from '../../composables/useRenderingPipeline'
import type { TFLite } from '../../composables/useTFLite'

type OfferSignal = {
  type: 'offer'
  offerId: string
  offer: RTCSessionDescriptionInit
}

type AnswerSignal = {
  type: 'answer'
  offerId: string
  answer: RTCSessionDescriptionInit
}

type IceCandidateSignal = {
  type: 'ice-candidate'
  offerId: string
  candidate: RTCIceCandidateInit
}

type SignalMessage = OfferSignal | AnswerSignal | IceCandidateSignal

const props = defineProps<{
  cameraPlayback: CameraPlayback
  backgroundConfig: BackgroundConfig
  segmentationConfig: SegmentationConfig
  postProcessingConfig: PostProcessingConfig
  bodyPix: BodyPix
  tflite: TFLite
}>()

const cameraPlayback = toRef(props, 'cameraPlayback')
const backgroundConfig = toRef(props, 'backgroundConfig')
const segmentationConfig = toRef(props, 'segmentationConfig')
const bodyPix = toRef(props, 'bodyPix')
const tflite = toRef(props, 'tflite')

const {
  pipeline,
  backgroundImageRef,
  canvasRef,
  fps,
  durations,
} = useRenderingPipeline(
  cameraPlayback,
  backgroundConfig,
  segmentationConfig,
  bodyPix,
  tflite
)

watch(
  () => props.postProcessingConfig,
  (config) => {
    pipeline.value?.updatePostProcessingConfig(config)
  },
  {
    deep: true,
    immediate: true,
  }
)

const statsText = computed(() => {
  const [resizingDuration = 0, inferenceDuration = 0, postProcessingDuration = 0] =
    durations.value

  return `${Math.round(fps.value)} fps (resizing ${resizingDuration}ms, inference ${inferenceDuration}ms, post-processing ${postProcessingDuration}ms)`
})

function parseSignalMessage(data: unknown): SignalMessage | null {
  if (typeof data !== 'string') {
    return null
  }

  try {
    const message = JSON.parse(data) as Partial<SignalMessage>
    if (
      message.type === 'offer' ||
      message.type === 'answer' ||
      message.type === 'ice-candidate'
    ) {
      return message as SignalMessage
    }
  } catch (error) {
    console.warn('Failed to parse signaling message.', error)
  }

  return null
}

watch(
  canvasRef,
  (canvas, _, onCleanup) => {
    if (!canvas) {
      return
    }

    const peerConnection = new RTCPeerConnection()
    const signalingChannel = new BroadcastChannel('signaling-channel')
    const localStream = canvas.captureStream()
    const pendingIceCandidates: RTCIceCandidateInit[] = []

    let currentOfferId: string | null = null
    let remoteDescriptionSet = false
    let answerInFlight = false
    let lastAnswer: RTCSessionDescriptionInit | null = null

    localStream.getTracks().forEach((track) => {
      peerConnection.addTrack(track, localStream)
    })

    peerConnection.onicecandidate = (event) => {
      if (!event.candidate || !currentOfferId) {
        return
      }

      signalingChannel.postMessage(
        JSON.stringify({
          type: 'ice-candidate',
          offerId: currentOfferId,
          candidate: event.candidate.toJSON(),
        })
      )
    }

    async function flushPendingIceCandidates() {
      for (const candidate of pendingIceCandidates) {
        await peerConnection.addIceCandidate(candidate)
      }
      pendingIceCandidates.splice(0, pendingIceCandidates.length)
    }

    async function answerOffer(message: OfferSignal) {
      if (currentOfferId === message.offerId && lastAnswer) {
        signalingChannel.postMessage(
          JSON.stringify({
            type: 'answer',
            offerId: message.offerId,
            answer: lastAnswer,
          })
        )
        return
      }

      if (answerInFlight) {
        return
      }

      currentOfferId = message.offerId
      remoteDescriptionSet = false
      lastAnswer = null
      pendingIceCandidates.length = 0
      answerInFlight = true

      try {
        await peerConnection.setRemoteDescription(
          new RTCSessionDescription(message.offer)
        )
        remoteDescriptionSet = true
        await flushPendingIceCandidates()

        const answer = await peerConnection.createAnswer()
        await peerConnection.setLocalDescription(answer)

        lastAnswer = answer
        signalingChannel.postMessage(
          JSON.stringify({
            type: 'answer',
            offerId: message.offerId,
            answer,
          })
        )
      } catch (error) {
        console.error('Failed to answer offer.', error)
      } finally {
        answerInFlight = false
      }
    }

    signalingChannel.onmessage = async (event) => {
      const message = parseSignalMessage(event.data)
      if (!message) {
        return
      }

      if (message.type === 'offer') {
        await answerOffer(message)
        return
      }

      if (!currentOfferId || message.offerId !== currentOfferId) {
        return
      }

      if (message.type === 'ice-candidate') {
        try {
          if (remoteDescriptionSet) {
            await peerConnection.addIceCandidate(message.candidate)
          } else {
            pendingIceCandidates.push(message.candidate)
          }
        } catch (error) {
          console.error('Failed to add ice candidate.', error)
        }
      }
    }

    onCleanup(() => {
      peerConnection.close()
      signalingChannel.close()
      localStream.getTracks().forEach((track) => track.stop())
    })
  },
  { immediate: true }
)
</script>

<template>
  <div class="output-viewer">
    <img
      v-if="backgroundConfig.type === 'image'"
      ref="backgroundImageRef"
      class="output-viewer__background"
      :src="backgroundConfig.url"
      alt=""
      :hidden="segmentationConfig.pipeline === 'webgl2'"
    />
    <canvas
      :key="segmentationConfig.pipeline"
      ref="canvasRef"
      class="output-viewer__canvas"
      :width="cameraPlayback.width"
      :height="cameraPlayback.height"
    />
    <div class="stats-bar">{{ statsText }}</div>
  </div>
</template>

<style scoped>
.output-viewer {
  position: relative;
  min-height: 100%;
  background:
    radial-gradient(circle at top right, rgba(138, 212, 255, 0.08), transparent 28%),
    linear-gradient(180deg, rgba(8, 15, 29, 0.26), rgba(8, 15, 29, 0.64));
}

.output-viewer__background,
.output-viewer__canvas {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.output-viewer__canvas {
  background: #020617;
}
</style>

// src/core/components/OutputViewer.tsx
import { createStyles, makeStyles, Theme } from '@material-ui/core/styles'
import Typography from '@material-ui/core/Typography'
import { BodyPix } from '@tensorflow-models/body-pix'
import { useEffect } from 'react'
import { BackgroundConfig } from '../helpers/backgroundHelper'
import { PostProcessingConfig } from '../helpers/postProcessingHelper'
import { SegmentationConfig } from '../helpers/segmentationHelper'
import { CameraPlayback } from '../helpers/cameraHelper'
import useRenderingPipeline from '../hooks/useRenderingPipeline'
import { TFLite } from '../hooks/useTFLite'

type OutputViewerProps = {
  cameraPlayback: CameraPlayback
  backgroundConfig: BackgroundConfig
  segmentationConfig: SegmentationConfig
  postProcessingConfig: PostProcessingConfig
  bodyPix: BodyPix
  tflite: TFLite
}

function OutputViewer(props: OutputViewerProps) {
  const classes = useStyles()
  const {
    pipeline,
    backgroundImageRef,
    canvasRef,
    fps,
    durations: [resizingDuration, inferenceDuration, postProcessingDuration],
  } = useRenderingPipeline(
    props.cameraPlayback,
    props.backgroundConfig,
    props.segmentationConfig,
    props.bodyPix,
    props.tflite
  )

  useEffect(() => {
    if (pipeline) {
      pipeline.updatePostProcessingConfig(props.postProcessingConfig)
    }
  }, [pipeline, props.postProcessingConfig])

  useEffect(() => {
    const peerConnection = new RTCPeerConnection()
    const signalingChannel = new BroadcastChannel('signaling-channel')

    const localStream = canvasRef.current.captureStream()
    localStream.getTracks().forEach((track) => {
      peerConnection.addTrack(track, localStream)
    })

    peerConnection.onicecandidate = (event) => {
      if (event.candidate) {
        console.log('Sending callee ICE candidate')
        signalingChannel.postMessage(
          JSON.stringify({ iceCandidate: event.candidate })
        )
      }
    }

    signalingChannel.onmessage = async (event) => {
      const message = JSON.parse(event.data)

      if (message.offer) {
        console.log('Received offer')
        const remoteDesc = new RTCSessionDescription(message.offer)
        await peerConnection.setRemoteDescription(remoteDesc)

        console.log('Sending answer')
        const answer = await peerConnection.createAnswer()
        await peerConnection.setLocalDescription(answer)
        signalingChannel.postMessage(JSON.stringify({ answer }))
      } else if (message.iceCandidate) {
        console.log('Received caller ICE candidate')
        await peerConnection.addIceCandidate(message.iceCandidate)
      }
    }

    return () => {
      peerConnection.close()
      signalingChannel.close()
    }
  }, [canvasRef])

  const statDetails = [
    `resizing ${resizingDuration}ms`,
    `inference ${inferenceDuration}ms`,
    `post-processing ${postProcessingDuration}ms`,
  ]
  const stats = `${Math.round(fps)} fps (${statDetails.join(', ')})`

  return (
    <div className={classes.root}>
      {props.backgroundConfig.type === 'image' && (
        <img
          ref={backgroundImageRef}
          className={classes.render}
          src={props.backgroundConfig.url}
          alt=""
          hidden={props.segmentationConfig.pipeline === 'webgl2'}
        />
      )}
      <canvas
        // The key attribute is required to create a new canvas when switching
        // context mode
        key={props.segmentationConfig.pipeline}
        ref={canvasRef}
        className={classes.render}
        width={props.cameraPlayback.width}
        height={props.cameraPlayback.height}
      />
      <Typography className={classes.stats} variant="caption">
        {stats}
      </Typography>
    </div>
  )
}

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      flex: 1,
      position: 'relative',
    },
    render: {
      position: 'absolute',
      width: '100%',
      height: '100%',
      objectFit: 'cover',
    },
    stats: {
      position: 'absolute',
      top: 0,
      right: 0,
      left: 0,
      textAlign: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.48)',
      color: theme.palette.common.white,
    },
  })
)

export default OutputViewer
